services:
  nginx:
    container_name: tesserarius-nginx
    restart: no
    image: nginx:1.26
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app
    depends_on:
      - php
      - postgres

  php:
    container_name: tesserarius-php
    restart: no
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./app:/app
      - ./.env:/.env
    depends_on:
      - postgres

  postgres:
    container_name: tesserarius-postgres
    restart: no
    image: postgres:16
    environment:
      POSTGRES_DB: tesserarius
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: database123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5432:5432"

  pgadmin:
    container_name: tesserarius-pgadmin
    restart: no
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin123
    volumes:
      - ./sql/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: { }